from typing import Dict, List, Union

"""Small offline movie catalog used when no TMDB_API_KEY is configured.

Seed movies use negative ids so they never collide with real TMDB ids,
making it obvious in the data which source a movie came from.
"""

SEED_MOVIES: List[Dict[str, Union[str, int]]] = [
    {
        "tmdb_id": -1,
        "title": "The Shawshank Redemption",
        "year": 1994,
        "poster_path": "",
        "overview": "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
        "director": "Frank Darabont",
        "runtime": 142,
        "genres": "Drama",
    },
    {
        "tmdb_id": -2,
        "title": "The Godfather",
        "year": 1972,
        "poster_path": "",
        "overview": "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
        "director": "Francis Ford Coppola",
        "runtime": 175,
        "genres": "Crime, Drama",
    },
    {
        "tmdb_id": -3,
        "title": "The Dark Knight",
        "year": 2008,
        "poster_path": "",
        "overview": "When the menace known as the Joker wreaks havoc on Gotham, Batman must accept one of the greatest psychological tests.",
        "director": "Christopher Nolan",
        "runtime": 152,
        "genres": "Action, Crime, Drama",
    },
    {
        "tmdb_id": -4,
        "title": "Pulp Fiction",
        "year": 1994,
        "poster_path": "",
        "overview": "The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.",
        "director": "Quentin Tarantino",
        "runtime": 154,
        "genres": "Crime, Drama",
    },
    {
        "tmdb_id": -5,
        "title": "Forrest Gump",
        "year": 1994,
        "poster_path": "",
        "overview": "The presidencies of Kennedy and Johnson, Vietnam, Watergate through the eyes of an Alabama man with an IQ of 75.",
        "director": "Robert Zemeckis",
        "runtime": 142,
        "genres": "Drama, Romance",
    },
    {
        "tmdb_id": -6,
        "title": "Inception",
        "year": 2010,
        "poster_path": "",
        "overview": "A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea.",
        "director": "Christopher Nolan",
        "runtime": 148,
        "genres": "Action, Sci-Fi",
    },
    {
        "tmdb_id": -7,
        "title": "The Matrix",
        "year": 1999,
        "poster_path": "",
        "overview": "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war.",
        "director": "Lana Wachowski, Lilly Wachowski",
        "runtime": 136,
        "genres": "Action, Sci-Fi",
    },
    {
        "tmdb_id": -8,
        "title": "Goodfellas",
        "year": 1990,
        "poster_path": "",
        "overview": "The story of Henry Hill and his life in the mob, covering his relationship with his wife and mob partners.",
        "director": "Martin Scorsese",
        "runtime": 145,
        "genres": "Crime, Drama",
    },
    {
        "tmdb_id": -9,
        "title": "Parasite",
        "year": 2019,
        "poster_path": "",
        "overview": "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the Kim clan.",
        "director": "Bong Joon Ho",
        "runtime": 133,
        "genres": "Drama, Thriller",
    },
    {
        "tmdb_id": -10,
        "title": "Spirited Away",
        "year": 2001,
        "poster_path": "",
        "overview": "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods and witches.",
        "director": "Hayao Miyazaki",
        "runtime": 125,
        "genres": "Animation, Fantasy",
    },
    {
        "tmdb_id": -11,
        "title": "Interstellar",
        "year": 2014,
        "poster_path": "",
        "overview": "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
        "director": "Christopher Nolan",
        "runtime": 169,
        "genres": "Adventure, Drama, Sci-Fi",
    },
    {
        "tmdb_id": -12,
        "title": "Fight Club",
        "year": 1999,
        "poster_path": "",
        "overview": "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into something much more.",
        "director": "David Fincher",
        "runtime": 139,
        "genres": "Drama",
    },
    {
        "tmdb_id": -13,
        "title": "The Lord of the Rings: The Fellowship of the Ring",
        "year": 2001,
        "poster_path": "",
        "overview": "A meek hobbit and eight companions set out on a journey to destroy the powerful One Ring.",
        "director": "Peter Jackson",
        "runtime": 178,
        "genres": "Adventure, Fantasy",
    },
    {
        "tmdb_id": -14,
        "title": "Se7en",
        "year": 1995,
        "poster_path": "",
        "overview": "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.",
        "director": "David Fincher",
        "runtime": 127,
        "genres": "Crime, Drama, Thriller",
    },
    {
        "tmdb_id": -15,
        "title": "La La Land",
        "year": 2016,
        "poster_path": "",
        "overview": "While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations.",
        "director": "Damien Chazelle",
        "runtime": 128,
        "genres": "Comedy, Drama, Romance",
    },
    {
        "tmdb_id": -16,
        "title": "Whiplash",
        "year": 2014,
        "poster_path": "",
        "overview": "A promising young drummer enrolls at a cutthroat music conservatory where his dreams of greatness are mentored by an instructor.",
        "director": "Damien Chazelle",
        "runtime": 106,
        "genres": "Drama, Music",
    },
    {
        "tmdb_id": -17,
        "title": "The Grand Budapest Hotel",
        "year": 2014,
        "poster_path": "",
        "overview": "A writer encounters the owner of an aging high-class hotel, who tells him of his early years as a lobby boy.",
        "director": "Wes Anderson",
        "runtime": 99,
        "genres": "Adventure, Comedy, Drama",
    },
    {
        "tmdb_id": -18,
        "title": "Get Out",
        "year": 2017,
        "poster_path": "",
        "overview": "A young African-American visits his white girlfriend's parents for the weekend, where his simmering uneasiness builds.",
        "director": "Jordan Peele",
        "runtime": 104,
        "genres": "Horror, Mystery, Thriller",
    },
    {
        "tmdb_id": -19,
        "title": "Everything Everywhere All at Once",
        "year": 2022,
        "poster_path": "",
        "overview": "A middle-aged Chinese immigrant is swept up into an insane adventure to save the multiverse.",
        "director": "Daniel Kwan, Daniel Scheinert",
        "runtime": 140,
        "genres": "Action, Adventure, Sci-Fi",
    },
    {
        "tmdb_id": -20,
        "title": "Dune",
        "year": 2021,
        "poster_path": "",
        "overview": "A noble family becomes embroiled in a war for control over the galaxy's most valuable asset on a desert planet.",
        "director": "Denis Villeneuve",
        "runtime": 155,
        "genres": "Adventure, Drama, Sci-Fi",
    },
]
